# =====================================================
# NOMBRE DE LA APLICACION
# =====================================================
spring.application.name=api

# =====================================================
# CONEXION CON BD
# =====================================================
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =====================================================
# CONFIGURACION JPA/HIBERNATE
# =====================================================
spring.jpa.show-sql=true
# Imprime SQL en consola (LOGS) -- DESACTIVAR EN PRODUCCION

spring.jpa.properties.hibernate.format_sql=true
# Formatea SQL (legible, con indentacion) -- DESACTIVAR EN PRODUCCION

# =====================================================
# MANEJO DE ERRORES
# =====================================================
server.error.include-stacktrace=never

# =====================================================
# JWT SECRET -- Usar variables de entorno en produccion
# =====================================================
api.security.token.secret=${JWT_SECRET}